config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#show', page: 'home'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  get '/pages/*page' => 'pages#show'
  post '/pages/create' => 'pages#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charges, only: %i[create new]
  resources :search, only: %i[index new]
  resources :domains, only: %i[index show create update] do
    with_options module: :domains do
      resource :unlock, only: :update
      resource :nameservers, only: :update
      resource :code, only: :show
      resources :records, only: %i[create update destroy]
    end
  end
  resources :transfers, only: :create
  resources :agreements, only: [:index]
  resources :notifications, only: %i[index destroy]
  resource :details, only: [:update]
  resource :carts, only: [:show]
  resources :items, only: %i[create update destroy]
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    @right_wrapper = 'carts/cart'
    @category = params[:category] || 0

    @results =
      if query.present?
        Suggester.new(query).call
      else
        []
      end

    respond_to do |format|
      format.html { render template: "search/index" }
      format.js
    end
  end

  def new
    @name = params[:name]
    @category = params[:category]

    @results = Availability.new(@name, @category).call
  end

  private

  def query
    params[:name]
  end
end

app/views/search/_name.html.slim
.panel.col-xs-12
  .panel-heading.col-xs-12
    .panel-title.col-xs-12
      a.col-xs-12.domain-name data-toggle="collapse" data-parent="#type_#{[@type.to_i]}" href="##{result}" = result
  .panel-collapse.collapse id="#{result}"
    .wrap
      .loading
        .bounceball
        .text Searching. Please wait...
    = form_with url: new_search_path, method: :get, remote: true, class: 'check-availability' do |f|
      = f.hidden_field :name, value: result
      = f.hidden_field :category, value: @category

app/views/search/_result.html.slim
.product.col-xs-12
  .domain.col-md-6.col-xs-8 = result["domain"]
  .price.col-md-3.col-xs-4
    |$
    = "%.2f " % (result["price"].to_i/100.0)
    span per year
  .buy.col-md-3
    = simple_form_for Item.new, remote: true do |f|
      = f.input :title, as: :hidden, input_html: {value: "#{result['domain']}"}
      = f.input :info, as: :hidden, input_html: {value: "#{result['domain']}"}
      = f.input :action, as: :hidden, input_html: {value: "buy"}
      = f.input :entity, as: :hidden, input_html: {value: "domain"}
      = f.input :duration, as: :hidden, input_html: {value: 1}
      = hidden_field_tag :authenticity_token, form_authenticity_token
      = f.button :button, "Add to cart", type: :submit, class: 'add-to-cart pull-right'

app/views/search/_results.html.slim
- results ||= @results
= render 'layouts/search'

.info-search.col-xs-12
	h5 = "<b>#{results.flatten.flatten.size - results.size}</b> available domains match your criteria. Click on a result to see available extensions!".html_safe if results

ul.nav.nav-tabs.domain-category.col-xs-12
  li.active.col-md-3.col-xs-6
    a data-toggle="tab" href="#home" data-category="0"  Top
  li.col-md-3.col-xs-6
    a data-toggle="tab" href="#menu1" data-category="1"  Cheap
  li.col-md-3.col-xs-6
    a data-toggle="tab" href="#menu2" data-category="2"  Professional
  li.col-md-3.col-xs-6
    a data-toggle="tab" href="#menu3" data-category="3"  New


.domain-group.alike.col-xs-12 Alike
#almost_exact.panel-group.col-xs-12
  - unless results&.any?
    .description Domains almost identical to your search query.
  = render partial: 'search/name', collection: results['almost_exact'], as: :result if results&.any?

.domain-group.misspelled.col-xs-12 Misspelled
#misspelled.panel-group.col-xs-12 
  - unless results&.any?
    .description It is common to have a misspelled word in your domain name. Google is an example!
  = render partial: 'search/name', collection: results['misspelled'], as: :result if results&.any?

.domain-group.with-prefix.col-xs-12 Prefix
#with_prefix.panel-group.col-xs-12
  - unless results&.any?
    .description Some popular examples: eBay, MySpace
  = render partial: 'search/name', collection: results['with_prefix'], as: :result if results&.any?

.domain-group.with-suffix.col-xs-12 Suffix
#with_suffix.panel-group.col-xs-12 
  - unless results&.any?
    .description Some popular examples: GitHub, LinkedIn, BlogSpot
  = render partial: 'search/name', collection: results['with_suffix'], as: :result if results&.any?

app/views/search/index.html.slim
= render 'results', results: @results

app/views/search/index.js.erb
// Update results count after each iteration
$('.info-search b').text(<%= @results.flatten.flatten.size - @results.size %>);

<% @results.each do |res| %>
  $("#<%= res.first %>").html("<%= escape_javascript (render partial: 'search/name', collection: res.last, as: :result) %>")
<% end %>


$('.panel-title .domain-name').on('click tap mouseenter', function(){
  if(!$(this).data('loaded')){
    $(this).parent().parent().parent().find('form.check-availability').submit();
  }
  $(this).data('loaded', true);
});

app/views/search/new.js.erb
var domain_id = "#<%= @name %>";
var results_count = <%= @results.count%>;
if(results_count>0){
  $(domain_id).html("<%= escape_javascript (render partial: 'search/result', collection: @results, as: :result) %>");
} else {
  $(domain_id).html("Sorry... There are no results. Why don't you try another category?");
}