config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#show', page: 'home'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  get '/pages/*page' => 'pages#show'
  post '/pages/create' => 'pages#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charges, only: %i[create new]
  resources :search, only: %i[index new]
  resources :domains, only: %i[index show create update] do
    with_options module: :domains do
      resource :unlock, only: :update
      resource :nameservers, only: :update
      resource :code, only: :show
      resources :records, only: %i[create update destroy]
    end
  end
  resources :transfers, only: :create
  resources :agreements, only: [:index]
  resources :notifications, only: %i[index destroy]
  resource :details, only: [:update]
  resource :carts, only: [:show]
  resources :items, only: %i[create update destroy]
end

app/models/detail/domain.rb
# frozen_string_literal: true

class Detail
  class Domain
    attr_reader :detail, :domain

    def initialize(detail, domain)
      @detail = detail
      @domain = domain
    end

    def call
      copy = detail.dup
      copy.user_id = nil
      copy.domain = domain
      copy.save
    end
  end
end

app/models/domain.rb
# frozen_string_literal: true

class Domain < ApplicationRecord
  include Domain::RemoteHelpers

  belongs_to :user

  has_many :nameservers
  has_many :records
  has_many :transactions, as: :item
  has_one :detail

  accepts_nested_attributes_for :nameservers
  accepts_nested_attributes_for :records
  # TODO: validate domain name

  enum status: { pending: 0, complete: 1, failed: 2 }

  def buy!
    Domain::Buyer.new(self).call
    update(status: :complete)
  rescue StandardError
    update(status: :failed) # :'(
  end

  def pricing!
    # TODO: when resellers, this is fixed instead of fetching it.
    @price ||= begin
                 remote_price = GoDaddy.available?(name).body['price']
                 normalized = remote_price / 10_000
                 price = Price.new(normalized).call
                 SpecialPrice.new(price, tld).call
               end
  end

  def agreements
    @agreements ||= Domain::Agreements.new(self).call
  end

  def agreement_keys
    agreements.map { |agreement| agreement['agreementKey'] }
  end

  def agreement_keys!
    @agreements = nil
    agreement_keys
  end

  def tld
    name.split('.').drop(1).join('.')
  end
end

app/models/domain/agreements.rb
# frozen_string_literal: true

class Domain::Agreements
  attr_reader :domain

  def initialize(domain)
    @domain = domain
  end

  def call
    response = GoDaddy.get_domain_agreements(tld, true)
    raise 'Could not get agreements keys' unless response.success?
    response.body
  end

  private

  def tld
    domain.tld
  end
end

app/models/domain/buyer.rb
# frozen_string_literal: true

require_dependency 'detail/null/go_daddy'

class Domain::Buyer
  attr_reader :domain

  def initialize(domain)
    @domain = domain
  end

  def call
    GoDaddy.purchase(
      domain: domain.name,
      period: domain.duration,
      renewAuto: domain.renewal,
      privacy: domain.privacy,
      consent: consent,
      nameServers: [],
      contactRegistrant: detail,
      contactAdmin: Detail::Null::GoDaddy.to_details,
      contactBilling: Detail::Null::GoDaddy.to_details,
      contactTech: Detail::Null::GoDaddy.to_details
    )
  end

  private

  def user
    @user ||= domain.user
  end

  def detail
    @detail ||= user.active_details.to_details
  end

  def consent
    @consent ||= Consent.new(user, domain).call
  end
end

app/models/domain/name_servers.rb
# frozen_string_literal: true

class Domain
  class NameServers
    attr_reader :domain, :name_servers

    def initialize(domain, name_servers)
      @domain = domain
      @name_servers = name_servers
    end

    def call
      GoDaddy.update_domain(domain.name, nameServers: name_servers)
    end
  end
end

app/models/domain/nameservers.rb
# frozen_string_literal: true

class Domain
  class Nameservers
    attr_reader :domain, :nameservers

    def initialize(domain)
      @domain = domain
    end

    def call
      response = GoDaddy.update_domain(domain.name,  nameServers: api_nameserver)

      raise 'Could not update nameservers of domain, try again later!' unless response.success?

      domain.update!(nameservers: nameservers)
    end

    private

    def api_nameservers
      nameservers.map { |n| { n.name => n.ip_addresses } }
    end
  end
end

app/models/domain/record.rb
class Domain
  class Record
    attr_reader :record

    def initialize(record)
      @record = record
    end

    def call
      GoDaddy.update_record(serialized_record)
    end

    def serialized_record
      [
        {
          type: record.kind,
          name: record.name,
          ttl: record.ttl,
          data: record.value
        }
      ]
    end
  end
end

app/models/domain/record_creator.rb
# frozen_string_literal: true

class Domain
  class RecordCreator
    attr_reader :domain

    def initialize(domain)
      @domain = domain
    end

    def call
      ::GoDaddy.update_records(domain.name, serialized_records)
    end

    def serialized_records
      @serialized ||= domain.records.map do |r|
        {
          type: r.kind.to_s,
          name: r.name,
          ttl: r.ttl,
          data: r.value
        }
      end
    end
  end
end

app/models/domain/remote_helpers.rb
# frozen_string_literal: true

class Domain
  module RemoteHelpers
    def unlocked?
      # GoDaddy.domain(name).response.body['status'] == 'UNLOCKED'
      false
    end
  end
end

app/models/domain/transfer.rb
# frozen_string_literal: true

class Domain
  class Transfer
    attr_reader :domain, :user, :unlock_code

    def initialize(user, name, unlock_code, privacy)
      @user = user
      @domain = user.domains.new(name: name, renewal: true, privacy: privacy)
      @unlock_code = unlock_code
    end

    def call
      response = GoDaddy.transfer_domain(
        domain.name,
        authCode: unlock_code,
        privacy: domain.privacy,
        renewAuto: domain.renewal,
        consent: consent
      )

      if response.success?
        domain.save!
      else
        raise 'Could not transfer'
      end
    end

    private

    def consent
      @consent ||= Consent.new(user, domain).call
    end
  end
end

app/models/domain/unlock_code.rb
# frozen_string_literal: true

class Domain
  class UnlockCode
    attr_reader :domain

    def initialize(domain)
      @domain = domain
    end

    def call
      return unlock_code unless unlock_code.blank?

      response = GoDaddy.get_domain(domain.name)

      raise 'Could not get Auth Code.' unless response.successful?

      domain.update!(unlock_code: response.body['domain']['authCode'])
      unlock_code
    end

    private

    def unlock_code
      domain.unlock_code
    end
  end
end

app/models/domain/unlocker.rb
# frozen_string_literal: true

class Domain
  class Unlocker
    attr_reader :domain

    def initialize(domain)
      @domain = domain
    end

    def call
      response = GoDaddy.update_domain(domain.name, locked: false)

      raise 'Could not unlock domain, try again later!' unless response.success?
    end
  end
end

app/models/go_daddy/client/domains.rb
# frozen_string_literal: true

module GoDaddy
  class Client
    module Domains
      def domains(*args)
        get('domains', *args)
      end

      def domain(name)
        get("domains/#{name}")
      end

      def update_domain(name, *args)
        patch("domains/#{name}", *args)
      end

      def delete_domain(name)
        delete("domains/#{name}")
      end

      def transfer_domain(name, *args)
        post("domains/#{name}/transfer", *args)
      end

      def available?(*names)
        if names.one?
          get('domains/available', domain: names.first)
        else
          post('domains/available', names.to_json)
        end
      end

      def suggest(name)
        get('domains/suggest', query: name)
      end

      def get_tlds
        get('domains/tlds')
      end

      def get_domain_agreements(*tlds, privacy)
        get('domains/agreements', privacy: privacy, tlds: tlds)
      end

      def get_domain_purchase_schema_tld(tld)
        get("domains/purchase/schema/#{tld}")
      end

      def validate_purchase(*args)
        post('domains/purchase/validate', *args)
      end

      def purchase(*args)
        post('domains/purchase', *args)
      end

      def update_records(name, *args)
        put("domains/#{name}/records", *args)
      end
    end
  end
end

app/controllers/domains/code.rb
class Domains::CodeController < ApplicationController
  before_action :login

  def show
    @domain = Domain.find(params[:domain_id])

    render json: Domain::UnlockCode.new(@domain).call
  rescue => e
    render json: { error: e.message }
  end
end

app/controllers/domains/code_controller.rb
# frozen_string_literal: true

class Domains::CodeController < ApplicationController
  before_action :login

  def show
    @domain = Domain.find(params[:domain_id])

    render json: Domain::UnlockCode.new(@domain).call
  rescue StandardError => e
    render json: { error: e.message }
  end
end

app/controllers/domains/nameservers_controller.rb
# frozen_string_literal: true

class Domains::NameserversController < ApplicationController
  before_action :login

  def update
    domain = current_user.domains.find(params[:domain_id])
    domain.update!(domain_params)
    Domain::UpdateNameserversJob.perform_later(domain)

    redirect_to domains_path, notice: "We've begun handling your nameservers."
  end

  private

  def domain_params
    params.require(:domain).permit(nameservers_attributes: %i[id name ip_addresses])
  end
end

app/controllers/domains/records_controller.rb
# frozen_string_literal: true

class Domains::RecordsController < ApplicationController
  before_action :login

  def create
    @domain = Domain.find(params[:domain_id])
    @record = @domain.records.create!(record_params)
    Domain::RecordCreator.new(@domain).call if @domain.records.where(kind: 'NS').count >= 2
    flash[:notice] = 'Record added.'
  end

  def update
    flash[:notice] = 'Record updated.'
    @domain = Domain.find(params[:domain_id])
    @record = Record.find(params[:id])
    @record.update!(record_params)
    Domain::RecordCreator.new(@domain).call if @domain.records.where(kind: 'NS').count >= 2
  end

  def destroy
    @record = Record.find(params[:id])
    @record_id = @record.id
    @record.destroy!
    flash[:notice] = 'Record destroyed.'
    # TODO: What happens when we destroy all records?
  end

  private

  def record_params
    params.require(:record).permit(:kind, :name, :value, :ttl, :priority, :service, :protocol, :port, :weight)
  end
end

app/controllers/domains/unlock_controller.rb
# frozen_string_literal: true

class Domains::UnlockController < ApplicationController
  before_action :login

  def update
    @domain = Domain.find(params[:domain_id])
    Domain::Unlocker.new(@domain).call

    # TODO: Check if successfully unlocked
    respond_to do |format|
      format.js { flash[:success] = "#{@domain.name} successfully unlocked." }
    end

    redirect_to domains_path, notice: e.message
  rescue StandardError => e
    redirect_to domains_path, notice: e.message
  end
end

app/controllers/domains_controller.rb
# frozen_string_literal: true

class DomainsController < ApplicationController
  before_action :login

  def index
    @right_wrapper = 'domains/index_nav'
    @domains = current_user.domains
  end

  def show
    @right_wrapper = 'domains/show_nav'
    @domain = current_user.domains.find(params[:id])
  end

  def create
    current_user.domains.create!(domain_params)
    redirect_to domains_path, notice: 'Domain bought!'
  end

  def update
    @domain = current_user.domains.find(params[:id])
    @domain.assign_attributes(domain_params)

    respond_to do |format|
      if @domain.save
        format.js { flash[:suceess] = 'Successfully updated.' }
      else
        format.html { render :show }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def domain_params
    params.require(:domain).permit(:name, :renewal)
  end
end

app/views/domains/_domain.html.slim
= link_to domain_path(domain), class: "domain col-xs-12" do
  .domain-name.col-xs-6 = domain.name
  .expiry.col-xs-6 
    | Expires: 
    = Time.new.strftime("%m/%d/%Y")

app/views/domains/_index_nav.html.slim
.col-xs-12.col-md-8.col-md-offset-2.simple-navigation
  ul.nav.nav-pills
    li.title Navigation
    li.active
      a data-toggle="pill" href="#domains" 
        | My Domains
    li 
      a#transfer-domain-button data-toggle="pill" href="#transfer" 
        | Transfer domains to Moonhythe

app/views/domains/_show_nav.html.slim
.col-xs-12.col-md-8.col-md-offset-2.simple-navigation
  ul.nav.nav-pills
    li.title Actions
    li.active
      a data-toggle="pill" href="#renew" 
        | Renew
    li 
      a data-toggle="pill" href="#contacts" 
        | Contact Information
    li 
      a data-toggle="pill" href="#records" 
        | Records
    li 
      a data-toggle="pill" href="#transfer" 
        | Transfer away

app/views/domains/index.html.slim
h2 My domains
hr
.tab-content.col-xs-12
  .content.col-xs-12.renew.tab-pane.fade.in.active id="domains"
    - if @domains.any?
      = render partial: 'domain', collection: @domains, as: :domain
    - else
      .description 
        | You don't have any domains with us, yet. You could 
        a data-toggle="pill" href="#transfer" onclick="$('#transfer-domain-button').click();"
          | transfer a domain to Moonhythe 
        | or 
        a href="/search" buy a new domain.

  .content.col-xs-12.tab-pane.fade id="transfer"
    .description To transfer a domain to Moonhythe, please follow the instructions
    ol.description
      li Unlock your domain from your current registrar
      li Enter your domain name, e.g. domain.com
      li Enter the authorization code you receive from your current registrar.
    = form_with url: transfers_path, remote: true, method: :post do |f|
      = f.text_field :name, label: false, placeholder: 'Domain name, e.g. domain.com'
      br
      = f.text_field :unlock_code, label: false, placeholder: 'Authorization code'
      br
      = f.submit 'Transfer', class: 'btn'
    hr
    h4 Incoming transfers

app/views/domains/new.html.slim
h3 Details
hr

= simple_form_for @detail, url: details_path, method: :put, remote: true, html: {class: "details-form"} do |f|
  .col-xs-12.col-md-6
    = f.input :first_name, required: true
    = f.input :last_name, required: true
    = f.input :organization
    = f.input :job_title
    = f.input :email, required: true
    = f.input :phone, required: true
  .col-xs-12.col-md-6
    = f.input :fax
    = f.input :address1, required: true
    = f.input :address2
    = f.input :city, required: true
    = f.input :state, required: true
    = f.input :postal_code, required: true
  = f.button :submit, 'Continue', class: 'pull-right proceed'

app/views/domains/show.html.slim
h2 
  | Manage 
  = @domain.name
hr
.tab-content.col-xs-12
  .col-xs-12.renew.tab-pane.fade.in.active id="renew"
    h4 Renew
    .description Automatic renewal protects you from losing your domain.
    = simple_form_for @domain, method: :put, remote: true do |f|
      = f.input :renewal, as: :radio_buttons, label: false
      = f.button :submit

  .col-xs-12.information.tab-pane.fade id="contacts"
    h4 Contact Information
    .description These are the details you have used to register your domain.

  .col-xs-12.records.tab-pane.fade id="records"
    h4 Records
    hr
    .head
      .col-xs-3 Type
      .col-xs-3 Name
      .col-xs-3 Value
      .col-xs-3 TTL 
    .body
      = render partial: 'domains/records/record', collection: @domain.records, as: :record
      = render partial: 'domains/records/record'

  .col-xs-12.forwarding.tab-pane.fade id="transfer"
    h4 Transfer
    .description We hope you had a great experience with us! Following are the steps on how to transfer your domain:
    ol.description
      li
        | To continue transfering, unlock your domain
        br
        - if @domain.unlocked?
          a.btn.btn-success Unlocked
        - else
          = form_with url: domain_unlock_path(@domain), remote: true, method: :put do |f|
            = f.submit "Unlock", class: 'btn'
        br
      li When the domain is unlocked, we will send you an email with an authorization code. Your new registrar will need it to transfer the domain.

app/views/domains/update.js.erb
$('.edit_domain').append("<%= escape_javascript (render partial: 'layouts/notice' if !flash.empty?) %>");