config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#show', page: 'home'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  get '/pages/*page' => 'pages#show'
  post '/pages/create' => 'pages#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charges, only: %i[create new]
  resources :search, only: %i[index new]
  resources :domains, only: %i[index show create update] do
    with_options module: :domains do
      resource :unlock, only: :update
      resource :nameservers, only: :update
      resource :code, only: :show
      resources :records, only: %i[create update destroy]
    end
  end
  resources :transfers, only: :create
  resources :agreements, only: [:index]
  resources :notifications, only: %i[index destroy]
  resource :details, only: [:update]
  resource :carts, only: [:show]
  resources :items, only: %i[create update destroy]
end

app/controllers/charges_controller.rb
# frozen_string_literal: true

class ChargesController < ApplicationController
  before_action :validate_purchase, only: :create

  def new
    @client_token = ChargeUser.token
    @amount = client_cart.total.to_i / 100.0
  end

  def create
    @items = client_cart.items

    current_user.update!(customer_id: customer)
    charge = ChargeUser.charge(nonce: nonce, amount: client_cart.total)

    @items.where(entity: 'domain').each do |item|
      domain = current_user.domains.create!(name: item.info, duration: item.duration, renewal: false, privacy: false, detail: current_detail)
      Domain::BuyJob.perform_later(domain, [charge[:id], charge.to_json])
    end

    redirect_to domains_path, notice: 'We have begun processing your domain. Please, review the default settings!'
  rescue StandardError => e
    redirect_to domains_path, notice: "Payment failed with: #{e.message}. Try again later..."
  end

  private

  def validate_purchase
    raise 'Invalid payment nonce.' unless params[:payment_method_nonce].present?
  end

  def nonce
    params[:payment_method_nonce]
  end
end

app/views/charges/new.html.slim
h2 Payment
= form_with url: charges_path do |f|
  #braintree-dropin
  = link_to 'Go back', carts_path
  = f.submit 'Complete', class: 'pull-right'

script src="https://js.braintreegateway.com/web/dropin/1.9.3/js/dropin.min.js"
javascript:
  document.addEventListener("turbolinks:load", function() {
    braintree.dropin.create({
      authorization: "#{@client_token}",
      container: '#braintree-dropin',
      paypal: {
        flow: 'checkout',
        amount: "#{@amount}",
        currency: 'USD'
      },
      paypalCredit: {
        flow: 'checkout',
        amount: "#{@amount}",
        currency: 'USD'
      },
      applePay: {
        displayName: 'Moonhythe',
        paymentRequest: {
          total: {
            label: 'Moonhythe',
            amount: "#{@amount}"
          }
        }
      }
    });
  })