config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#show', page: 'home'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  get '/pages/*page' => 'pages#show'
  post '/pages/create' => 'pages#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charges, only: %i[create new]
  resources :search, only: %i[index new]
  resources :domains, only: %i[index show create update] do
    with_options module: :domains do
      resource :unlock, only: :update
      resource :nameservers, only: :update
      resource :code, only: :show
      resources :records, only: %i[create update destroy]
    end
  end
  resources :transfers, only: :create
  resources :agreements, only: [:index]
  resources :notifications, only: %i[index destroy]
  resource :details, only: [:update]
  resource :carts, only: [:show]
  resources :items, only: %i[create update destroy]
end

app/views/layouts/_footer.html.slim
/! Footer
footer.page-footer.indigo.center-on-small-only.pt-0
  .container
    .row
      .col-md-12
        .footer-socials.mb-5.flex-center
          a.icons-sm.fb-ic
            i.fa.fa-facebook.fa-lg.white-text.mr-md-4
          a.icons-sm.tw-ic
            i.fa.fa-twitter.fa-lg.white-text.mr-md-4
          a.icons-sm.gplus-ic
            i.fa.fa-google-plus.fa-lg.white-text.mr-md-4
          a.icons-sm.li-ic
            i.fa.fa-linkedin.fa-lg.white-text.mr-md-4
          a.icons-sm.ins-ic
            i.fa.fa-instagram.fa-lg.white-text.mr-md-4
          a.icons-sm.pin-ic
            i.fa.fa-pinterest.fa-lg.white-text
  .footer-copyright
    .container-fluid
      | © 2016 Copyright:
      a href="https://www.MDBootstrap.com"  MDBootstrap.com

app/views/layouts/_header.html.slim
header.main-header
  = link_to 'Moonhythe', root_path, class: "logo"
  a.cd-nav-trigger href="#0" 
    span

app/views/layouts/_notice.html.slim
#flash-messages
  -flash.each do |key, value|
    = content_tag(:div, value, :class => "flash #{key}") 

javascript:
  setTimeout(function(){
      $('body #flash-messages').fadeOut();
  },($('body #flash-messages .flash').text().length)*70);

app/views/layouts/_search.html.slim
.col-xs-12.domain-search
  = form_tag search_index_path, remote: true, method: 'get', class: 'domain-search col-xs-12' do
      = text_field_tag :name, params[:name], placeholder: "Keywords", class: 'col-xs-11 autofocus', autocomplete: 'off', autocorrect: 'off', onfocus: "this.removeAttribute('readonly');"
      = hidden_field_tag :category, 0
      button.search-btn.col-xs-1 type="submit"
        .text-center = icon('fab', 'searchengin fa-2x')

app/views/layouts/_sidenav.html.slim
nav.cd-side-nav.col-md-2.col-xs-12
  ul
    li.cd-label Main
    li.search class="#{'active' if controller_name == 'search'}"
      = link_to "Search domains", search_index_path
    - if current_user
      li.domains class="#{'active' if controller_name == 'domains'}"
        = link_to "My Domains", domains_path
      li.notifications class="#{'active' if controller_name == 'notifications'}"
        = link_to "Notifications", notifications_path
      li.profile class="#{'active' if controller_name == 'registrations'}"
        = link_to "My profile", edit_user_registration_path
    - else
      li.login class="#{'active' if controller_name == 'sessions'}"
        = link_to "Log in", new_user_session_path
      li.signup class="#{'active' if controller_name == 'registrations'}"
        = link_to "Sign up", new_user_registration_path

  ul.secondary
    li.cd-label Secondary
    li.has-children.more
      a.trigger href='' More
      ul.hidden
        li.faq class="#{'active' if params[:page] == 'faq'}"
          a href="/pages/faq"  FAQ
        li.support class="#{'active' if params[:page] == 'support'}"
          a href="/pages/support"  Support
        li.contacts class="#{'active' if params[:page] == 'contacts'}"
          a href="/pages/contacts"  Contacts
        li.about.hidden class="#{'active' if params[:page] == 'about'}"
          a href="/pages/about"  About
        li.document class="#{'active' if params[:page] == 'privacy'}"
          a href="/pages/privacy"  Privacy Policy 
        li.document class="#{'active' if params[:page] == 'terms'}"
          a href="/pages/terms"  Terms & Conditions
        li.credits class="#{'active' if params[:page] == 'credits'}"
          a href="/pages/credits"  Credits

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"]
    meta[name="keywords" content="domain,name,generator,suggester,ideas"]
    meta[name="description" content="Easily browse through sensibly selected domain names separated in categories. Search by purpose, price and more!"]
    = favicon_link_tag 'favicon.ico'
    title Generate domain name | Suggestion tool
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = analytics_init if GoogleAnalytics.valid_tracker?
  body
    -unless params[:page] && (['home']).include?(params[:page])
      = render 'layouts/header'
      #flash
      main.cd-main-content
        = render 'layouts/sidenav'
        .content-wrapper.col-xs-12.col-md-6.col-md-offset-2
          = yield
        .right-wrapper.col-xs-12.col-md-4
            = render @right_wrapper if @right_wrapper.present?
    -else
      = yield